version: '3'

services:
  mysqldb:
    image: mysql:5.7
    #    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: clashOfStudents
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/DatabaseDump.sql:/docker-entrypoint-initdb.d/DatabaseDump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
    restart: always
    ports:
      - "8081:80"

  minio1:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./mindata:/data
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
      MINIO_ACCESS_KEY: IQ8WmkoR6EoyZtWIH4Pc
      MINIO_SECRET_KEY: c7SiP3sIexrTxQH8yTak5zSxBYdIpLTCuxA1qsSk
    command: server /data --console-address ":9001"

  webgl:
    container_name: unity-webgl-demo
    image: unity-webgl-demo
    build: ./webgl
    ports:
      - "8080:80"

  #microservices
  course_service:
    build: ./microservices/courseService
    ports:
      - "5003:80"
    restart: always
    environment:
      DB: mysqldb

  email_service:
    build: ./microservices/emailService
    ports:
      - "1001:80"
    restart: always
    environment:
      DB: mysqldb

  jwt_service:
    build: ./microservices/jwtService
    ports:
      - "1002:80"
    restart: always
    environment:
      DB: mysqldb

  question_service:
    build: ./microservices/questionService
    ports:
      - "1003:80"
    restart: always
    environment:
      DB: mysqldb
      MINIO: minio1

  score_service:
    build: ./microservices/scoreService
    ports:
      - "5002:80"
    restart: always
    environment:
      DB: mysqldb

  user_management_service:
    build: ./microservices/userManagementService
    ports:
      - "1000:80"
    restart: always
    environment:
      DB: mysqldb

  ranking_service:
    build: ./microservices/rankingService
    ports:
      - "5004:80"
    restart: always
    environment:
      DB: mysqldb

  backend_service:
    build: ./backend
    ports:
      - "1999:80"
    restart: always
    environment:
      DB: mysqldb
      COURSESERVICE: course_service
      EMAILSERVICE: email_service
      JWTSERVICE: jwt_service
      QUESTIONSERVICE: question_service
      SCORESERVICE: score_service
      USERSERVICE: user_management_service
      RANKINGSERVICE: ranking_service

volumes:
  dbdata:
