version: '3'

services:
  mysqldb:
    image: mysql:5.7
#    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: clashOfStudents
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/DatabaseDump.sql:/docker-entrypoint-initdb.d/DatabaseDump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
    restart: always
    ports:
      - "8081:80"

  minio1:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - mindata:/data
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
      MINIO_ACCESS_KEY: IQ8WmkoR6EoyZtWIH4Pc
      MINIO_SECRET_KEY: c7SiP3sIexrTxQH8yTak5zSxBYdIpLTCuxA1qsSk
    command: server /data --console-address ":9001"

  webgl:
    container_name: unity-webgl-demo
    image: unity-webgl-demo
    build: ./webgl
    ports:
      - "8080:80"





volumes:
  dbdata:
  mindata:
